Do not skip recurring includes of files with no include guard.
Viatorus/quom pull request #53
Opened 2023-04-14 08:57 UTC by MaxSagebaum

Hello,

thanks for providing the tool.  I used it on our library and it worked nearly out of the box.

We have some common patterns where the code is written in `.tpp` files. These files have no include guard and are included multiple times. quom added them the first time but afterwards the include was skipped.

The patch changes the logic of quom and adds files to the `__processed_files` list only when an include guard is present.

I hope you find the patch useful.

Cheers

Max

2023-04-14 09:47 UTC, Viatorus requested changes
Thank you for using quom and for the contribution.

Could you add a unit test for this change?

2023-04-14 09:47 UTC, Viatorus commented on src/quom/quom.py
> +    def __has_guard(self, tokens: list[Token]):
To support older python versions:

```suggestion
    def __has_guard(self, tokens: List[Token]):
```

2023-04-14 11:00 UTC, MaxSagebaum commented
Sure. I added a new test, that checks the new behavior. I hope it is ok.

`setup.py` test was not working for me. It always gave:
```
running build_ext

----------------------------------------------------------------------
Ran 0 tests in 0.000s

OK
```

With some warnings beforehand.

2023-04-14 21:02 UTC, MaxSagebaum commented
Sure. Commit is up. But github is currently not "seeing" it in this pull request.

2023-04-15 10:36 UTC, merged

2023-04-15 11:41 UTC, Viatorus commented
@MaxSagebaum 
I fixed it. Thanks again for using Quom. :) Version 4.0.1 does have your changes

2023-04-17 06:11 UTC, MaxSagebaum commented
Thanks for providing the tool.